name: Deploy

on:
  push:
    branches:
      - master

  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages
        run: npm install && npm install --prefix client
      - name: Eslint
        run: npm run lint
      - name: Build
        run: npm run build
      # - name: Unit tests
      #   run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:5000
      - name: Deploy to Heroku
        # Skip deploy if the commit message contains '#skip'
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'rostyslavsynenko'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: 'https://rostyslavsynenko.herokuapp.com/api/health'
          checkstring: 'ok'
          delay: 60
          rollbackonhealthcheckfailed: true
        env:
          HD_MONGO_URI: ${{secrets.MONGO_URI}}
          HD_JWT_SECRET: ${{secrets.JWT_SECRET}}
          HD_JWT_EXPIRE: ${{secrets.JWT_EXPIRE}}
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        # Skip versioning if the commit message contains '#skip'
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: 'patch'
