name: Scheduled health check

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the app's health
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://rostyslavsynenko.herokuapp.com/
          follow-redirect: no
          max-attempts: 3
          retry-delay: 20s
